### ISSUE TITLE
Allow Esc key to always close dialog (no file selected) - p3

### ISSUE THREAD

**Issue by DaveJarvis** [io7m/jwheatsheaf#14]
Minor issue.

1. Open File chooser
1. Single-click **Recent items**
1. Press `Esc` key

Expected: File chooser dialog closes.

Actual: File chooser dialog remains open.

Regardless of what File chooser dialog widget has focus, the Esc key should always close the dialog window, returning an empty list. This is another reason why having a separate dialog to navigate to a new directory is probably not used by other OS-level file choosers: pressing Esc would have to close _both_ dialogs in succession. Easier not to deal with two dialogs.

**Comment by io7m** [comment]
Yep, seems fine.
