### ISSUE TITLE
Allow setting the initial file name - p1

### ISSUE THREAD

**Issue by DaveJarvis** [io7m/jwheatsheaf#15]
The JavaFX `FileChooser` API includes `setInitialFileName` that provides a way to save the user some keystrokes when the most likely file name is known, computable, or otherwise predictable. For example, if a user is editing "filename.md" and then elects to export as a PDF file, the dialog could pre-populate the file name input field with "filename.pdf".

**Comment by io7m** [comment]
:+1:
