### ISSUE TITLE
Update README to include description - p5

### ISSUE THREAD

**Issue by DaveJarvis** [io7m/jwheatsheaf#16]
> I'm just glad someone's noticed jwheatsheaf exists.

Perhaps update the README file to include a few keywords in the description that makes the software easier to find:

> An alternative to JavaFX's `FileChooser` that aims to be feature-compatible, if not fully API-compatible.

**Comment by io7m** [comment]
I don't know, there's sometimes a benefit to be had in having no users. :laughing:
