### ISSUE TITLE
Allow confirmation when user opts to replace existing file for export or save as - p1

### ISSUE THREAD

**Issue by DaveJarvis** [io7m/jwheatsheaf#17]
The JavaFX `FileChooser` provides build-in functionality to confirm replacing a file. Porting this behaviour would be useful. This relates to https://github.com/io7m/jwheatsheaf/issues/7#issuecomment-815508744

For example:

1. Open File chooser in "SAVE AS" or "EXPORT" mode as per comment (e.g., `FileAccess.SAVE_AS`, or `FileAccess.EXPORT`)
1. Double-click a file
1. File chooser opens a "Confirmation Dialog"
1. Confirmation Dialog prompts user to overwrite (has **OK** and **Cancel** buttons, as per `ButtonBar` order)
1. Click **OK** for Confirmation Dialog to close, File chooser to close, and then return selected file name; or
1. Click **Cancel** (or press Esc, or click "X" in dialog window) to close Confirmation Dialog but keep File chooser dialog open

**Comment by io7m** [comment]
I've generally been handling this in the application itself, because this kind of code is subject to "time of check, time of use" issues. I suppose it's harmless enough to perform an extra check in the dialog, but I'd like a way to opt-out.

**Comment by io7m** [comment]
Completed as of https://github.com/io7m/jwheatsheaf/commit/1c8fcbbf757592640dc165de7be2219bb17ccadc.
