### ISSUE TITLE
Allow embedding File chooser as a modeless operational view - p2

### ISSUE THREAD

**Issue by ghost** [io7m/jwheatsheaf#18]
In KeenWrite, there exists a `FilesView` class, which provides a dockable tab (see screenshot, below) for selecting files. Essentially, the `FilesView` is a File chooser that's not a dialog and allows users to open files at any time. There's a _lot_ of overlap between the `FilesView` and the File chooser, including:

* Icon for file type
* Input field for pasting directory name (followed by pressing `Enter`)
* Sortable table that lists file names, dates, times, and sizes
* Event-driven to notify of file selection (via arrow keys + `Enter` or double-click)

Having the File chooser be a bit more modular would enable its reuse both for modal dialogs and for modeless views.

![keenwrite-files-view](https://user-images.githubusercontent.com/2131950/114091887-18831380-986e-11eb-8051-e1368858487d.png)

In the screenshot above, the upper-left button can be clicked to open a directory chooser; in effect, it'd be like the File chooser in modeless operation opening a File chooser in modal operation. Here's what this currently looks like:

![keenwrite-files-view-chooser](https://user-images.githubusercontent.com/2131950/114093384-e5da1a80-986f-11eb-85c1-a7952eff64c2.png)

It'd be nice to use File chooser for both to get a consistent user experience.

**Comment by io7m** [comment]
Yes, I'd like to do something along these lines as well. I'm intending (at a later date) to develop a very simple window-in-window system for JavaFX. Picture something like a simulation of a desktop-over-VNC. That'll involve being able to embed things like `jwheatsheaf` into into objects that aren't JavaFX `Stage` objects.

**Comment by DaveJarvis** [comment]
> simple window-in-window system for JavaFX

I reviewed a wide variety of such systems, the results of which may be of interest:

https://github.com/DaveJarvis/PitchDockFX
