### ISSUE TITLE
Allow including and excluding files from the list using globbing pattern - p3

### ISSUE THREAD

**Issue by DaveJarvis** [io7m/jwheatsheaf#19]
Sometimes users (or developers) may wish to hide certain files. It would be convenient to use a globbing pattern in such cases. For example, consider the following API:

``` java
  /**
   * Sets the list of file names to display. For example, a single call to
   * this method with values of ("**.pdf", "Portable Document Format (PDF)")
   * would display only a file listing of PDF files.
   *
   * @param glob        Pattern that allows matching file names to be listed.
   * @param description Human-readable description of the pattern.
   */
  void addIncludeFileFilter( String glob, String description );

  /**
   * Sets the list of file names to suppress. For example, a single call to
   * this method with values of (".*") would prevent listing files that begin
   * with a period.
   *
   * @param glob Pattern that allows matching file names to be suppressed.
   */
  void addExcludeFileFilter( String glob );
```

Multiple calls would be permitted, as well as mixing. Such as:

``` java
builder.addIncludeFileFilter( "**.md, **.Rmd, **.markdown", "Markdown Files" );
builder.addIncludeFileFilter( "*.ps, **.eps", "(Encapsulated) PostScript" );
builder.addExcludeFileFilter( ".*" ); // Don't show hidden files
```

This API is a bit simpler, IMO, than creating `JWFileChooserFilterType` instances. (It's syntactic sugar, really.)

Given that the user cannot select excluded files, it needs no description. See [FileSystem.getPathMatcher](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/nio/file/FileSystem.html#getPathMatcher(java.lang.String)) for globbing details.

**Comment by io7m** [comment]
I need to think about this a bit. For uniformity, I'd like to keep the implementation itself based around filters, but we could use a more terse API to create them (similar to the above example) and to allow for one or more filters to be invisibly and always enabled.

**Comment by io7m** [comment]
I'd like to nail down the semantics of globbing filters. An isolated "include" glob is easy to understand, as is an isolated "exclude" glob. Combining arbitrary includes and excludes is somewhat less easy to understand, and there are many different ways to interpret the combinations.

I generally favour the semantics provided by [sequential evaluation with explicit halts](https://github.com/io7m/gtyrell#inclusionsexclusion-filters). Would this be acceptable if I put a pleasant API over it?

**Comment by DaveJarvis** [comment]
I see what you mean. 

``` java
builder.addIncludeFileFilter( "**.{md,Rmd,markdown}", "Markdown Files" );
builder.addExcludeFileFilter( "*.*md" );
```

I'd expect that all `.Rmd` files would be listed, but no `.cmd` files. Call order is imperative, yes, and forcing it is fine. It may even be enforced by throwing an exception. Haven't fully thought this through, but the following examples should probably throw:

``` java
// Don't permit exclude before include?
builder.addExcludeFileFilter( "*.*md" );
builder.addIncludeFileFilter( "**.{md,Rmd,markdown}", "Markdown Files" ); // throw?

// Don't permit include after exclude?
builder.addIncludeFileFilter( "**.{md,Rmd,markdown}", "Markdown Files" );
builder.addExcludeFileFilter( "*.*md" );
builder.addIncludeFileFilter( "**.{md,text}", "Text Files" );  // throw?
```

**Comment by io7m** [comment]
You might want to take a look at the `feature/globbing-19` branch. There's information in the `README.md` file now about how the API works, and various unit tests.

**Comment by io7m** [comment]
I've merged the `globbing-19` branch. Additions/changes should be specified in new tickets.
