### ISSUE TITLE
Allow distinction between opening files and opening directories - p0

### ISSUE THREAD

**Issue by DaveJarvis** [io7m/jwheatsheaf#20]
The JavaFX `FileChooser` has the ability to select either files or directories. This is helpful when the application allows the user to select a particular path without permitting selection of a file. For example, if the user has a set of images in a directory, it simplifies development to ensure that the user may only select the images directory, not an image within it.

This has implications on the behaviour for choosing files. For example:

1. Configure File chooser to be file-centric (as opposed to directory-centric)
1. Open File chooser
1. Select a directory
1. Press `Enter` (or click `Open`)

Expected: File chooser navigates into selected directory (because configured to choose _files_, not directories).

Actual: File chooser selects the directory name and passes it back to the application.

**Comment by io7m** [comment]
I'm fine with extending the API to cope with this.

**Comment by io7m** [comment]
I'm thinking actually that I'd like to keep the behaviour of the "Open" button consistent. That is:

* Clicking a file in the directory listing selects that file as a candidate for opening
* Double clicking a _file_ in the directory listing does nothing
* Double clicking a _directory_ in the directory listing _always_ navigates to that directory
* Clicking the "Open" button (if enabled) _always_ opens the selected file(s).

That is, it's a departure from the inconsistent (and poorly-accessible) behaviour that native file choosers often provide, where if a file chooser is configured to select only files, and you click a directory and click the "Open" button, you navigate into that directory.

The behaviour I'd like to see is that if the file chooser is configured to select files, then the "Open" button is only enabled when one or more _files_ are selected. If the file chooser is configured to select _directories_, then the "Open" button is only enabled when one or more directories are selected. Navigation via the directory listing is unchanged.

**Comment by DaveJarvis** [comment]
Side topic: https://osherove.com/blog/2005/4/3/naming-standards-for-unit-tests.html

At work, I've been asking people to name unit test methods with those three parts. To make the names a bit more Java-friendly, there are four parts:

    test_UnitOfWork_Inputs_ExpectedOutcome()

For example:

* test_DirectoryMode_SingleClickDirectory_CandidateSelected()
* test_DirectoryMode_SingleClickFile_NothingSelected()
* test_DirectoryMode_DoubleClickDirectory_DirectoryNavigated()
* test_AnyMode_ClickOpenButton_SelectedItemsReturned()

Your thoughts?

**Comment by io7m** [comment]
Seems fine to me! Names of tests haven't carried much significance until now (there's usually a Javadoc comment above the test method explaining what's supposed to happen).

**Comment by DaveJarvis** [comment]
I've also included a Robot Delegate concept to eliminate some of the boilerplate and, I hope, improve clarity of intent within the tests. Example:

``` java
    final var delegate = new RobotDelegate(robot);
    final var okButton = delegate.getOkButton();

    robot.sleep(1L, SECONDS);
    FxAssert.verifyThat(okButton, NodeMatchers.isDisabled());
    robot.clickOn(delegate.getFileNameTableCell( "README.TXT"));
    FxAssert.verifyThat(okButton, NodeMatchers.isEnabled());
    robot.clickOn(okButton);
```

**Comment by io7m** [comment]
Implemented as of https://github.com/io7m/jwheatsheaf/commit/7981434ff9c9dea7df508a2e8fef06fe5aa07505
