### ISSUE TITLE
Use file system's default for builder default - p4

### ISSUE THREAD

**Issue by DaveJarvis** [io7m/jwheatsheaf#21]
Code that opens a file chooser and select at most one file, minimally is documented as:

``` java
final var configuration =
  JWFileChooserConfiguration.builder()
    .setFileSystem(FileSystems.getDefault())
    .build();
```

Consider making `FileSystems.getDefault()` the default configuration setting, which changes the minimum to:

``` java
final var configuration =
  JWFileChooserConfiguration.builder().build();
```

**Comment by io7m** [comment]
Seems OK. Keep in mind that the specified filesystem has to be the same filesystem used in all `Path` values in the configuration.
