### ISSUE TITLE
Allow sorting by file type, file name, file size, and last modified time - p3

### ISSUE THREAD

**Issue by DaveJarvis** [io7m/jwheatsheaf#22]
Users have become accustomed to sorting various file attributes to help them find and select files faster. KeenWrite's [FilesView](https://github.com/DaveJarvis/keenwrite/blob/master/src/main/java/com/keenwrite/ui/explorer/FilesView.java) class has code that demonstrates how to provide sorting abilities. Here's a snippet of the relevant parts:

``` java
    final var table = new TableView<FilesView.PathEntry>();
    final TableColumn<PathEntry, Path> colType = createColumn( "Type" );
    final TableColumn<PathEntry, String> colName = createColumn( "Name" );

    colType.setCellFactory( new FileCell<>() );

    colType.setCellValueFactory( stat -> stat.getValue().typeProperty() );
    colName.setCellValueFactory( stat -> stat.getValue().nameProperty() );

    final var columns = table.getColumns();
    columns.add( colType );
    columns.add( colName );

    table.getSortOrder().setAll( colName, ... );

    colType.setComparator(
      // Sorts the "type" based on file name extension
      comparing( p -> getExtension( p.getFileName().toString() ) )
    );
```

The [PathEntry](https://github.com/DaveJarvis/keenwrite/blob/4520ee8a46defb88cc3f303a71ed2c602f614c8b/src/main/java/com/keenwrite/ui/explorer/FilesView.java#L243) is an inner class, very bean-esque in nature. It could probably be changed to a record at some point.

**Comment by io7m** [comment]
Does this not already happen if you click the column headers?

**Comment by DaveJarvis** [comment]
> Does this not already happen if you click the column headers?

Not on Linux/XFCE.

**Comment by io7m** [comment]
I'll look into it. I'm on a system that's fairly close to that.
