### ISSUE TITLE
Allow inclusion of ".." to change to parent directory - p4

### ISSUE THREAD

**Issue by DaveJarvis** [io7m/jwheatsheaf#23]
In addition to the up-arrow button, it is convenient to have a ".." directory entry so that when navigating using the keyboard the user can select ".." followed by pressing `Enter` to navigate up without having to tab or click with the mouse. For example:

1. Open File chooser
1. Click into the tabular list of file names
1. Navigate to the top of the list (e.g., press Home or Page Up)
1. Navigate down one item (e.g., press Down arrow)
1. Press `Enter`

Expected: File chooser navigates into parent directory; directories of "." and ".." both exist.

Actual: The ".." directory is not listed.

**Comment by io7m** [comment]
I forget why I excluded `..` originally. Adding it back in seems harmless.
