### ISSUE TITLE
Allow Control and Shift click to select discontinuous ranges - p4

### ISSUE THREAD

**Issue by ghost** [io7m/jwheatsheaf#26]
A fairly nuanced use of file pickers entails selecting discontinuous ranges of files, which is functionality available by intermixing `Ctrl` and `Shift` key combinations. For example:

1. Open File chooser with a list of 10 items
1. Click 1st list entry
1. Press `Shift` key
1. Click 3rd list entry (the first three items are selected)
1. Release `Shift` key
1. Press `Ctrl` key
1. Click 5th list entry
1. Press `Ctrl` key (do not release `Shift`)
1. Click the 8th list entry
1. Release both keys

Expected: Two selection ranges, 1st through 3rd and 5th through 8th.

Actual: Three selections, range of 1st through 3rd, single 5th, and single 8th.

**Comment by io7m** [comment]
Yeah, we're currently at the mercy of JavaFX's defaults for table row selection. It seems to me that combining `Ctrl+Shift` just behaves as if you'd only held `Ctrl` at the moment. I'm wondering if there's somewhere that these can be adjusted in the `TableView` API...

**Comment by DaveJarvis** [comment]
https://stackoverflow.com/a/32029580/59087 ?

**Comment by io7m** [comment]
Looks like that's attempting to solve a problem we don't have. :disappointed: 

To be clear: Right now:
*  `Ctrl` click allows for adding and removing individual items from the set of selected items. 
* `Shift` allows for _replacing_ the current set of selected items with the range of items between the previous and current click position. 

What we want is to be able to combine aspects of the two with `Ctrl+Shift`: `Ctrl+Shift` clicking in two places should add or remove items to/from the current set of selected items. This is likely going to require some custom code; I think JavaFX is more or less treating `Ctrl+Shift` as `Ctrl` right now.
