### ISSUE TITLE
Allow pressing Enter to accept file name - p2

### ISSUE THREAD

**Issue by DaveJarvis** [io7m/jwheatsheaf#28]
1. Open File chooser (to SAVE a file)
1. Click File name text field (note: text field should have focus when dialog first opens)
1. Type `12.pdf` (ensure that the **Save** button is enabled)
1. Press `Enter`

Expected: Full path to `12.pdf` is returned to the application and the dialog closes.

Actual: Nothing happens.

**Comment by io7m** [comment]
This isn't _quite_ what you asked for, but I believe the implementation is slightly better in terms of predictability: Pressing return completes the text field, and selects the item in the directory, and then shifts focus to the Open button. Pressing return a second time will obviously then press the Open button.
