### ISSUE TITLE
Allow traversal to path when entered - p2

### ISSUE THREAD

**Issue by DaveJarvis** [io7m/jwheatsheaf#29]
When pasting a path into the input field, the File chooser navigates to the leaf's parent directory, rather than the leaf directory.

1. Open File chooser
1. Click button to enter full path directly
1. Paste a complete path to an existing directory (e.g., `/home/username/dev/java/keenwrite/docs`)
1. Press `Enter`

Expected: List of all files inside `docs` directory appears.

Actual: List of all files inside `keenwrite` directory appears.

Work around

Append `/.` to the path to ensure navigation is successful.

Relates to #13

**Comment by io7m** [comment]
Nice catch!
