### ISSUE TITLE
Changing File type is not responsive - p1

### ISSUE THREAD

**Issue by ghost** [io7m/jwheatsheaf#33]
Replicate:

1. Create a new File chooser.
1. Add a file filter to exclude files matching the glob pattern `**/.*`.
1. Open the File chooser in a directory with fewer than 50 hidden files/directories and fewer than 10 regular files.
1. Set **File type** to the exclude file pattern.

Expected:

* The **File type** drop-down opens instantly.
* Upon selecting the exclude filter, the file listing is updated instantly.
* Scrolling file listing is snappy.

Actual:

* The drop-down takes about 0.5s to open.
* Selecting a different exclude filter takes about 0.75s.
* Scrolling the file list is jerky and unresponsive.

Any ideas what's causing these delays? (If it was 10,000 files, I could understand a teeny tiny delay, but using a 3GHz processor alongside 32GB RAM reading from a super-fast SSD, I'd anticipate nearly instantaneous response times even for 10k files, much less ~50.)

The previous version does not exhibit such behaviour. It seems likely that the filters are causing the issues.

See #32 for a minimal example.

**Comment by io7m** [comment]
I'm just seeing this one now. Apparently I never got a notification!

I should be able to take a look at this today... We certainly shouldn't be seeing these kinds of performance issues.

**Comment by io7m** [comment]
Any chance you could get this into a test case so that I can throw CI at it on various platforms? I'm unable to reproduce it on any of my local machines here.

What JVM is showing this behaviour?

**Comment by DaveJarvis** [comment]
> Any chance you could get this into a test case so that I can throw CI at it on various platforms?

Probably not until September.

> What JVM is showing this behaviour?

``` bash
$ java -version
openjdk version "16.0.1" 2021-04-20
OpenJDK Runtime Environment (build 16.0.1+9)
OpenJDK 64-Bit Server VM (build 16.0.1+9, mixed mode, sharing)
```

https://bell-sw.com/pages/downloads/#/java-16-current

**Comment by io7m** [comment]
> Probably not until September.

Ok, that's not a problem. Whenever you can get to it!

Looks like I'm still on at most JDK 15. Using the new glob-based filters will be potentially more I/O heavy because they have to ask the filesystem to create new glob matchers, and they have to check `Files.isDirectory` for each path twice. I wouldn't expect that to cause a regression like this though.

Is this exclusive to the new glob filters?

**Comment by DaveJarvis** [comment]
> Is this exclusive to the new glob filters?

Seems likely, given that that's the new feature I tried to use, but cannot say with 100% certainty.

**Comment by io7m** [comment]
I've never been able to reproduce this, and the OP is gone!
