### ISSUE TITLE
Allow for specifying custom dialog titles

### ISSUE THREAD

**Issue by io7m** [io7m/jwheatsheaf#8]
Allow for specifying custom dialog titles. Less generic than "Please select one or more files...".

**Comment by DaveJarvis** [comment]
Yes, please! There are a number of different titles in my application:

``` java
    final var dialog = createFileChooser( "Dialog.file.choose.save.title" );
    final var dialog = createFileChooser( "Dialog.file.choose.export.title" );
    final var dialog = createFileChooser( "Dialog.file.choose.open.title" );
```

Being able to configure these would be in keeping with functionality offered by `FileChooser`.
